name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # jalan tiap hari jam 00:00 UTC (07:00 WIB)
  workflow_dispatch:      # bisa dijalankan manual lewat tab Actions

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: mdafaadiwinata
          outputs: |
            dist/snake-dark.svg

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
